name = "Fabulously Optimized"
author = "robotkoer"
version = "9.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ae3e0f8d841b85b3ae0ad955b7924158150e0777c0b0f3a89b87fd5b107062b"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
