name = "bs_craft"
author = "robotkoer"
version = "9.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45d689b9240762421547ec9a71b130f0e994ec0f228715a33f39cc86996f0185"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
