name = "bs_craft"
author = "robotkoer"
version = "9.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f69f59eeadc5a2983e9541377ca022673e27e9a9c65d81595c83b2c886749e82"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
