name = "bs_craft"
author = "robotkoer"
version = "9.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93575ca5d26fb4b1c7882aed3d2876a808d9a38c32c3ab44e1333df7178d31e6"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
